name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Check Python syntax
      run: |
        python -m py_compile app.py
        python -m py_compile config.py
        find models routes -name "*.py" -exec python -m py_compile {} \;
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          bash /root/deploy-service-center.sh
    
    - name: Notify on failure
      if: failure()
      run: echo "Deployment failed! Check logs."
